leftnav:
- identifier: 2af8d3ef-aa4a-424e-bb25-3a50bc07dd72
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: f7a25d27-e322-4900-ba82-1e4efca7bad7
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 844bcf70-9c1d-433f-b805-788ee06f83e7
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 5f9f81f5-e4c0-468b-afd0-d8b0f42e88b2
  name: Lecture Slides
  url: /pages/lecture-slides
  weight: 40
- identifier: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  name: Scenarios
  url: /pages/scenarios
  weight: 50
- identifier: fb422766-748d-47a2-867d-1e5e54682b37
  name: Final Exam
  url: /pages/final-exam
  weight: 60
- identifier: 593db1b1-549f-42b1-86eb-4b1027a6f444
  name: 'Scenario #1'
  parent: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  url: /pages/scenario-1-the-traditional-negotiation-game
  weight: 10
- identifier: ff4cc5c0-893a-4fa7-af45-865f901c0e48
  name: 'Scenario #2'
  parent: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  url: /pages/scenario-2-the-consensus-building-approach
  weight: 20
- identifier: b793b25f-f4cc-4f66-876c-b6392c09cffe
  name: 'Scenario #3'
  parent: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  url: /pages/scenario-3-facilitation
  weight: 30
- identifier: ee006516-2ada-47e9-882b-505120291ee1
  name: 'Scenario #4'
  parent: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  url: /pages/scenario-4-gender-and-negotiation
  weight: 40
- identifier: d385740e-ce43-4798-92a5-9e2f16b929c5
  name: 'Scenario #5'
  parent: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  url: /pages/scenario-5-roles-and-responsibilities-of-public-sector-mediators
  weight: 50
