leftnav:
- identifier: 2af8d3ef-aa4a-424e-bb25-3a50bc07dd72
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: f7a25d27-e322-4900-ba82-1e4efca7bad7
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 844bcf70-9c1d-433f-b805-788ee06f83e7
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 4179d1c0-7094-4d60-ae8b-e4c80e993b15
  name: Scenarios
  url: /pages/scenarios
  weight: 40
- identifier: fb422766-748d-47a2-867d-1e5e54682b37
  name: Final Exam
  url: /pages/final-exam
  weight: 50
